### ISSUE TITLE
Measuring performance and evaluating network

### ISSUE THREAD

**Issue by realamirhe** [trieschlab/SORNSim#5]
I'm trying to evaluate network performance duo to accuracy metrics.

So I added A Supervisor behavior to the last `neuron_group` and release or suppress dopamine
in response to network prediction.

Know I want to evaluate the network after some iteration(episode) for the latest calculated synapse weights.

I tried this thing, but there is some barrier within this method.
```python
network = Network()
# add ng and s to networks
# start training
network.simulate_iterations(ITERATIONS)

# whats evaluation❓
network.recording_off()
network.simulate_iterations(ITERATIONS)
```

1. Iteration doesn't get rested and continue from its last state, 
So my supervisor who used something like this will now fail.

```python
output = self.outputs[neurons.iteration - 1]
prediction = neurons.fired
```
I can make it circular e.g. (`(neurons.iteration - 1) % len(self.output)`) but it seems hacky for me.

2. We can deactivate the mechanism, is there a way to deactivate a behavior conditionally 
for example, adding accuracy metrics in the testing (evaluating) phase but not training.

Although it might be possible to hack around this mechanism, I wanted to know how the maintainer uses the package.

## Context
I'm trying to implement delayed learning through the re-enforcement reward system.

**Comment by realamirhe** [comment]
When I attempt the UI version, I get the identical scenario I described in my initial inquiry.
I utilized a circular `%` that can observe the network and output in a rounded row. Any solution for it would be appreciated as well.

**Comment by realamirhe** [comment]
I believe we can consider this action as a good one.

```python
network.recording_off()
network.iteration = 0
```
 
 Also for the learning process, I guess it can be then be cut off in `new_iteration`
 
```python
class SynapseSTDP(Behaviour):
    def set_variables(self):
       # the same as before
    def new_iteration(self, synapse):
        if not synapse.recording:
            return
        # the same as before
```

**Comment by gitmv** [comment]
Hello,
1.

"network.interation" or "neuron.iteration" is supposed to show the total number of cycles the network has gone through and will alsways increase at each cycle.

Of course you can always just reset it with "network.iteration = 0" which should not result in any issues because the variable is not used internally (maybe for some ui tabs).

If you are just interested in the last neurons.outputs values and they are numpy array you can just use neurons.outputs[-1] or neurons.outputs[-ITERATIONS:] or something similar.

im not sure whether i understand the circular thing. If you want to realease dopamine after some cycles and some consitions you could do it like this:

    def new_iteration(self, neuron):
        if neuron.iteration%100==0:
            #do prediction
            #release dopamine?


2.

like you said, you can alway wrap your new_iteration content into an if statement to make the behaviour conditionally.

you can also add some supervisor behaviour which turns some other modules on and off by calling 
if condition: 
neurons.network.deactivate_mechanisms('module tag')

or 
if condition: 
neurons.network.activate_mechanisms('module tag')

in general i would just put the evaluation, testing, executing and module activation/deactivation into the main file like this for example:

net=Network(...)
# initialization

#run training iterations

#net.activate_mechanisms(some mechanism tags)

#maybe reset some states

#run evaluation iterations

#net.deactivate_mechanisms(some other tags...)

#...

#some plotting

#...

**Comment by realamirhe** [comment]
Thank you for your explanation

> im not sure whether i understand the circular thing. If you want to realease dopamine after some cycles and some consitions you could do it like this:

In UI mode iteration is not bounded to `network.simulate_iterations` iteration, it increases through time or via GUI buttons. meanwhile, when your labeled data is not infinite, you are going to reach the end of it soon or later. So I came up with passing data and output in circular order, meaning whenever we reach the end we are going to reset `index=0` and start from the beginning of both again.


For sake of clarity about the #initialization section, you have suggested,
Is there any example/toy code that did what you said, I'm interested in seeing the evaluation phase.

**Comment by realamirhe** [comment]
Could you provide me an example (even at an abstract level), How can I change the input-stimulus shape and record the new `n.fired` for example.

```python
trainging_stimulus = ...
ng_input = NeuronGroup(..., 
                       behaviour={..., 
                         1: InputStimulus(stimulus=trainging_stimulus),
                         # ...
                         9: Recorder(tag="tag", variables=["n.v", "n.fired"]),
                       })
                       
network.simulate_iterations(len(trainging_stimulus))

# Evaluation
testing_stimulus = ...
network.recording_off()
network.iteration = 0
network.NeuronGroups[0].behaviour[1].stimulus = testing_stimulus
network.simulate_iterations(len(testing_stimulus))     
```

This causes a change in normal behavior I made but not effect in Recorder

**Comment by gitmv** [comment]
Ok now i understand.
There are many options how to build something like this.

Of course
`index = neuron.iteration % labeled_data_length `

could give you the index for repeated pattern activation.

But i think this is not the best solution for your problem, because you want to execute the training and testing stimulus in an alternating fashion.

I think the best way would be something like this:

```python
trainging_stimulus = ...
testing_stimulus = ...

ng_input = NeuronGroup(..., 
                       behaviour={..., 
                         1: InputStimulus(tag='train', stimulus=trainging_stimulus),
                         2: InputStimulus(tag='test', stimulus=testing_stimulus),
                         # ...
                         9: Recorder(tag="rec", variables=["n.v", "n.fired"]),
                       })
               
# initialize

for loop in range(???):
        network.activate_mechanisms('train')
        network.deactivate_mechanisms('test')
        network['train',0].index=0 # [tag,0] is equivalent to [tag][0] and gives you the first found object with the given tag
        network.simulate_iterations(len(trainging_stimulus))
        recorded = network["n.fired", 0] 
        network['rec', 0].reset()

        network.deactivate_mechanisms('train')
        network.activate_mechanisms('test')
        network['test',0].index=0
        network.simulate_iterations(len(testing_stimulus))
        recorded = network["n.v", 0]
        network['rec',0].reset()

#increase the self.index variable inside of the InputStimulus module at each step.
```
this example makes use of the tagging system, but of course you can also access the recorder and other behaviours via
`network.NeuronGroups[0].behaviour[?] ... `

I hope this was helpful :)
