### ISSUE TITLE
network.initialize now passing info as True as default

### ISSUE THREAD

**Issue by realamirhe** [trieschlab/SORNSim#6]
The latest update of PymoNNto has changed the default info from False to true.
So there we will face an issue of save_param of None
`storage_manager.save_param('info', desc)`
we need to update do one of the following

```
# revert the info flag to default False
network.initialize(info=False)

# add the storage_manager 
network.initialize(storage_manager=StorageManager('network'))

# reset git to the old release 
git reset --hard f80c8e
```

Is there a possibility of adding a changelog for the project?
Is the minor update safe or we should revert the PymoNNto to its latest release.

https://github.com/trieschlab/PymoNNto/commit/7111cfe7014534cbf6daeb9a92b32ab63ecba5ad#diff-1b8a4cbe3fd166904effcd07067c3ba3cc250ac580e3f7a1b24442a17d33a547R130

**Comment by gitmv** [comment]
Thank you for finding this bug!

I forgot to add a check whether the storage manager is None. There are test cases but all the tests had a Storagemanager added by default. 

In the new commit the bug is fixed.

In most cases the commit message is used as some kind of "changelog".
An overview can be generated with: git log --pretty="- %s"

But of course a more detailed propper changelog, at least for the core code, should be added in the future.

Otherwise the commit should be save to use because there were no mayor changes to the model execution. The info flag is only used to display and store information about the current network.
